on: push

jobs:
	hello_world_job:
		runs-on: ubuntu-latest
		name: Tarea para saludar
		setps:
			- name: Hola mundo action step
			  id: hello
			  uses: action/Clase-10-9@v1
			  with:
			   who-to-greet: 'Bruno'
			# Use the outpu from the "Hello" step
			- name: Obtener la hora de salida
			  run: echo "La fecha y hora es ${{ steps.hello.outputs.time }}"